#!/usr/bin/env bash

TOKENFORGE_UNITY_VERSION="${TOKENFORGE_UNITY_VERSION:-6000.4.10f1}"
UNITY_APP_PATH="${UNITY_APP_PATH:-/Applications/Unity/Hub/Editor/${TOKENFORGE_UNITY_VERSION}/Unity.app}"
UNITY_PATH="${UNITY_PATH:-${UNITY_APP_PATH}/Contents/MacOS/Unity}"
UNITY_MANAGED_PATH="${UNITY_MANAGED_PATH:-${UNITY_APP_PATH}/Contents/Managed}"

export TOKENFORGE_UNITY_VERSION
export UNITY_APP_PATH
export UNITY_PATH
export UNITY_MANAGED_PATH
